SELECT ub.TITLE, ub.BOARD_ID, ur.REPLY_ID, ur.WRITER_ID, ur.CONTENTS, DATE_FORMAT(ur.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD ub
JOIN USED_GOODS_REPLY ur ON ub.BOARD_ID = ur.BOARD_ID
WHERE ub.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY ur.CREATED_DATE ASC, ub.TITLE ASC;